# Generated by Django 2.0.3 on 2018-03-11 11:31

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
            ],
            options={
                'verbose_name': 'event',
                'verbose_name_plural': 'events',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('filename', models.CharField(max_length=255, verbose_name='filename')),
                ('imagefile', models.ImageField(max_length=255, upload_to='photos/', verbose_name='file')),
                ('timestamp', models.DateTimeField(null=True, verbose_name='timestamp')),
                ('thumb', models.ImageField(blank=True, max_length=255, null=True, upload_to='photos/thumbnails', verbose_name='thumbnail')),
                ('uploaded', models.DateTimeField(auto_now_add=True, verbose_name='uploaded')),
                ('latitude', models.CharField(blank=True, max_length=20, null=True, verbose_name='latitude')),
                ('longitude', models.CharField(blank=True, max_length=20, null=True, verbose_name='longitude')),
                ('address', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('exif', django.contrib.postgres.fields.jsonb.JSONField()),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='photos.Event')),
            ],
            options={
                'verbose_name': 'photo',
                'verbose_name_plural': 'photos',
                'ordering': ['-uploaded'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='photo',
            name='tags',
            field=models.ManyToManyField(to='photos.Tag'),
        ),
        migrations.AddField(
            model_name='photo',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='uploaded by'),
        ),
    ]
