# Generated by Django 2.0.3 on 2018-03-10 11:52

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('filename', models.CharField(max_length=255, verbose_name='filename')),
                ('imagefile', models.ImageField(max_length=255, upload_to='photos/', verbose_name='file')),
                ('timestamp', models.DateTimeField(null=True, verbose_name='timestamp')),
                ('thumb', models.ImageField(blank=True, max_length=255, null=True, upload_to='photos/thumbnails', verbose_name='thumbnail')),
                ('uploaded', models.DateTimeField(auto_now_add=True, verbose_name='uploaded')),
                ('exif', django.contrib.postgres.fields.jsonb.JSONField()),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='uploaded by')),
            ],
            options={
                'verbose_name': 'photo',
                'verbose_name_plural': 'photos',
                'ordering': ['-uploaded'],
            },
        ),
    ]
