# Generated by Django 2.0.3 on 2018-03-11 13:10

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_auto_20180311_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='address',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
