# Generated by Django 2.0.3 on 2018-03-10 17:28

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_photo_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='address',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
