# Generated by Django 2.0.3 on 2018-03-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_photo_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='location',
        ),
        migrations.AddField(
            model_name='photo',
            name='latitude',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='photo',
            name='longitude',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='longitude'),
        ),
    ]
