# Generated by Django 2.0.3 on 2018-03-14 20:58

from django.db import migrations, models
import photos.models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_auto_20180314_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='import',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='uploaded'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='imagefile',
            field=models.ImageField(max_length=255, upload_to=photos.models.directory_path, verbose_name='file'),
        ),
    ]
