# Generated by Django 2.0.3 on 2018-03-14 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_auto_20180314_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='import',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='uploaded'),
        ),
    ]
