# Generated by Django 2.0.3 on 2018-03-15 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0007_auto_20180314_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='import',
            name='slug',
            field=models.CharField(default=' ', max_length=255, verbose_name='slug'),
            preserve_default=False,
        ),
    ]
