# Generated by Django 2.0.3 on 2018-04-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0009_auto_20180315_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='import',
            name='timestamp',
            field=models.DateTimeField(verbose_name='uploaded'),
        ),
    ]
