# Generated by Django 2.0.3 on 2018-04-04 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0010_auto_20180402_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='tags',
            field=models.ManyToManyField(blank=True, to='photos.Tag'),
        ),
    ]
