# Generated by Django 2.0.7 on 2018-07-20 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0011_auto_20180404_1856'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-timestamp'], 'verbose_name': 'photo', 'verbose_name_plural': 'photos'},
        ),
    ]
