# Generated by Django 2.2.9 on 2020-01-26 15:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photos', '0012_auto_20180720_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='public',
            field=models.BooleanField(default=False, verbose_name='Public'),
        ),
        migrations.AddField(
            model_name='photo',
            name='shared',
            field=models.ManyToManyField(related_name='shared_with', to=settings.AUTH_USER_MODEL, verbose_name='Shared with'),
        ),
    ]
