# Generated by Django 2.2.9 on 2020-01-26 15:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0013_auto_20200126_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='shared',
            field=models.ManyToManyField(blank=True, related_name='shared_with', to=settings.AUTH_USER_MODEL, verbose_name='Shared with'),
        ),
    ]
