# Generated by Django 3.0.3 on 2020-03-01 10:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photos', '0017_auto_20200202_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='visible_for',
            field=models.ManyToManyField(blank=True, related_name='visisble_for', to=settings.AUTH_USER_MODEL, verbose_name='Visible for'),
        ),
    ]
