# Generated by Django 3.0.6 on 2020-05-15 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0019_event_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-timestamp'], 'verbose_name': 'event', 'verbose_name_plural': 'events'},
        ),
    ]
