# Generated by Django 3.1 on 2020-08-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0020_auto_20200515_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='address',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='exif',
            field=models.JSONField(),
        ),
    ]
