# Generated by Django 4.0.6 on 2022-07-13 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0022_rename_event_gallery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='event',
            new_name='gallery',
        ),
    ]
