# Generated by Django 4.0.6 on 2022-07-24 09:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photos', '0024_alter_gallery_options_alter_photo_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='visible_for',
            field=models.ManyToManyField(blank=True, related_name='visible_for', to=settings.AUTH_USER_MODEL, verbose_name='Visible for'),
        ),
    ]
