# Generated by Django 2.0.3 on 2018-03-14 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersettings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersettings',
            options={'verbose_name': 'user settings', 'verbose_name_plural': 'user settings'},
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='recent',
            field=models.PositiveIntegerField(verbose_name='number of recent photos'),
        ),
    ]
