# Generated by Django 2.0.3 on 2018-04-02 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersettings', '0002_auto_20180314_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='recent',
            field=models.PositiveIntegerField(help_text='0 means no limit', verbose_name='number of recent photos'),
        ),
    ]
