# Generated by Django 3.0.2 on 2020-01-28 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersettings', '0003_auto_20180402_1734'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersettings',
            options={'verbose_name': 'Benutzereinstellungen', 'verbose_name_plural': 'Benutzereinstellungen'},
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='recent',
            field=models.PositiveIntegerField(help_text='0 bedeutet keine Einschränkung', verbose_name='Anzahl letzte Fotos'),
        ),
    ]
