# Generated by Django 3.0.3 on 2020-02-05 17:58

from django.db import migrations, models
import django.db.models.deletion
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('usersettings', '0005_auto_20200204_0945'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='theme',
            options={'ordering': ['name'], 'verbose_name': 'Thema', 'verbose_name_plural': 'Themen'},
        ),
        migrations.AlterField(
            model_name='theme',
            name='cssfile',
            field=filebrowser.fields.FileBrowseField(blank=True, max_length=255, verbose_name='CSS Datei'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usersettings.Theme', verbose_name='Thema'),
        ),
    ]
