# Generated by Django 3.0.3 on 2020-03-02 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersettings', '0007_remove_usersettings_recent'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='recent',
            field=models.DateField(blank=True, help_text='None means all', null=True, verbose_name='recent photos since'),
        ),
    ]
