# Generated by Django 3.0.3 on 2020-03-03 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersettings', '0008_usersettings_recent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='recent',
        ),
    ]
