# Generated by Django 3.0.3 on 2020-03-03 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersettings', '0009_remove_usersettings_recent'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='recent',
            field=models.PositiveSmallIntegerField(default=0, help_text='None means all', verbose_name='Recent photos from last days'),
        ),
    ]
