# Generated by Django 3.0.3 on 2020-03-03 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersettings', '0010_usersettings_recent'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='limit',
            field=models.PositiveSmallIntegerField(default=0, help_text='0 means no limit', verbose_name='Limit unfiltered amount of photos'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='recent',
            field=models.PositiveSmallIntegerField(default=0, help_text='0 bedeutet keine Einschränkung', verbose_name='Fotos der letzten Tage'),
        ),
    ]
