# Generated by Django 3.0.3 on 2020-03-10 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersettings', '0011_auto_20200303_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='limit',
            field=models.PositiveSmallIntegerField(default=0, help_text='0 bedeutet keine Einschränkung', verbose_name='Anzahl Fotos ohne Filter begrenzen auf'),
        ),
    ]
