# Generated by Django 4.0.3 on 2022-04-06 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersettings', '0015_auto_20200828_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='photos_per_page',
            field=models.PositiveSmallIntegerField(default=20, verbose_name='Photos per page'),
        ),
    ]
