# Generated by Django 4.0.3 on 2022-04-06 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersettings', '0016_usersettings_photos_per_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='limit',
        ),
    ]
