# Generated by Django 4.0.6 on 2022-07-13 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersettings', '0017_remove_usersettings_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='photos_per_page',
            field=models.PositiveSmallIntegerField(default=20, verbose_name='Fotos pro Seite'),
        ),
    ]
